# Power management config
## Milliseconds of inactivity before entering idle state (30 min = 30*60*1000ms)
CONFIG_ZMK_IDLE_TIMEOUT=1800000
## Enable deep sleep support
CONFIG_ZMK_SLEEP=y
## Milliseconds of inactivity before entering deep sleep (2 hours = 2*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000
## Enable soft off support
CONFIG_ZMK_PM_SOFT_OFF=y
